package:
    name:
    version:
    rel: 1
    archive: false
    delete: true

sources:
    - url:
      md5:
      sha256:

patches:
    - url:
      md5:

prepare: |

build: |

check: |

install: |

final: |


required:
    -
recommended:
    -
optional:
    -

description: ""
